// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbXiO0cgJpH6mMcnjTn6GAAe8tqwOLEQA',
    appId: '1:655575876288:web:3b989b19554bc64b58e325',
    messagingSenderId: '655575876288',
    projectId: 'llom-23d56',
    authDomain: 'llom-23d56.firebaseapp.com',
    storageBucket: 'llom-23d56.firebasestorage.app',
    measurementId: 'G-WLHP90X2T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuQqbvJzu8u3u39hXgEmojPPkSeJj4QcA',
    appId: '1:655575876288:android:e8ccf0db0e190f5158e325',
    messagingSenderId: '655575876288',
    projectId: 'llom-23d56',
    storageBucket: 'llom-23d56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJg5t8n_wz4s6rqcjmbulIKaxR1xgR0IY',
    appId: '1:655575876288:ios:c300b92e92d6c07a58e325',
    messagingSenderId: '655575876288',
    projectId: 'llom-23d56',
    storageBucket: 'llom-23d56.firebasestorage.app',
    iosClientId: '655575876288-1h99t07ep8tq97d3djhisbel6pbqmfo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.llom',
  );
}
